transporte_aragon:
  usuario : 
  contr : 
  customerId : 

  host_aragon : https://api.masternautconnect.com/
  api_base_url : connect-webservices/services/public/v1/customer/{customerId}/

  api_list_vehicles : vehicle
  api_list_driver : driver
  api_live_position_latest : tracking/live/latest
  api_vehicle_journey_history_latest : tracking/history/vehicle/latest?fromDateTime={fromDateTime}&vehicleId={vehicleIds}
  api_distance_travelled : tracking/journey/summary?startDate={startDate}&endDate={endDate}&vehicleIds={vehicleIds}

transporte_zaragoza:
  host_zaragoza : http://api.consorciozaragoza.es/
  api_base_url : api/1/

  api_lines : lines
  api_stops : stops
  api_routes : routes/{id}
  api_stops_route : stops_route/{id_linea}/{id_ruta}/{sentido}
  api_arrival_time : arrival_time/{code_parada}
  api_notices : notices
  api_origins : origins
  api_destinations : destinations/{id}
  api_lines_ori_des : lines_ori_des/{Origen}/{Destino}
  api_times_route : times_route/{id_linea}/{bus}/{departure_time}/{direction}
  api_exp_ori_des : exp_ori_des/{Origen}/{Destino}
  api_stops_ori_des : stops_ori_des/{Origen}/{Destino}
  api_arrival_ori_des : arrival_ori_des/{Origen}/{Destino}
  api_sae : sae