common_config:
  secret_key: foo
  debug: true
  databases:
    default:
      ENGINE: foo
      NAME: foo
projects:
  api_reader:
    transport:
      aragon:
        user: foo
        password: foo
        customer_id: foo
        base_url: foo
        endpoints:
          vehicles: foo
          drivers: foo
          live_position_latest: foo
          vehicle_journey_history_latest: foo
          distance_travelled : foo
      zaragoza:
        base_url: foo
        endpoints:
          lines: foo
          stops: foo
          routes: foo
          stops_route: foo
          arrival_time: foo
          notices: foo
          origins: foo
          destinations: foo
          lines_ori_des: foo
          times_route: foo
          exp_ori_des: foo
          stops_ori_des: foo
          arrival_ori_des: foo
          sae: foo
