version: "3.9"

services:
  web:
    build: .
    command: /bin/sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: ga-od-core
    volumes:
      - gaodcore:/usr/src/app
    ports:
      - "8001:8000"
volumes:
  gaodcore:
    driver: local
