services:
  ga-od-core:
    build: .
    command: /bin/sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: ga-od-core
    ports:
      - "8001:8000"
volumes:
  gaodcore:
    driver: local
