# Generated by Django 3.1.13 on 2021-08-17 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaodcore_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectorconfig',
            name='enabled',
            field=models.BooleanField(help_text='Resource will be offered if conector and resource are enabled.'),
        ),
        migrations.AlterField(
            model_name='connectorconfig',
            name='id',
            field=models.AutoField(help_text='Primary key of ConnectorConfig.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='connectorconfig',
            name='name',
            field=models.CharField(help_text='Human readable name. This must be identificable and unique.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='connectorconfig',
            name='uri',
            field=models.TextField(help_text='This can have and http/s API or database URI. Ex. "https://domain.es/file.ext" or "oracle://username:password@host".', unique=True),
        ),
        migrations.AlterField(
            model_name='resourceconfig',
            name='connector_config',
            field=models.ForeignKey(help_text='Foreign key of ConnectorConfig.', on_delete=django.db.models.deletion.CASCADE, to='gaodcore_manager.connectorconfig'),
        ),
        migrations.AlterField(
            model_name='resourceconfig',
            name='enabled',
            field=models.BooleanField(help_text='Resource will be offered if ConectorConfig and ResourceConfig are enabled.'),
        ),
        migrations.AlterField(
            model_name='resourceconfig',
            name='id',
            field=models.AutoField(help_text='Primary key of ConnectorConfig.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resourceconfig',
            name='name',
            field=models.CharField(help_text='Human readable name. This must be identificable and unique.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='resourceconfig',
            name='object_location',
            field=models.CharField(help_text='Only used in database resources. it can be a table, view, fucntion, etc. APIs resources must be null.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resourceconfig',
            name='object_location_schema',
            field=models.CharField(help_text='Only used in database resources. Is not required if are in default schema. APIs resources must be null.', max_length=255, null=True),
        ),
    ]
