# Generated by Django 3.1.14 on 2024-07-04 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gaodcore_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceSizeConfig",
            fields=[
                (
                    "resource_id",
                    models.ForeignKey(
                        help_text="Foreign key of ResourceConfig.",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="gaodcore_manager.resourceconfig",
                    ),
                ),
                (
                    "registries",
                    models.BigIntegerField(
                        help_text="Number of resgistries of the resource", null=True
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(
                        help_text="Size in Mb of the resource ", null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="connectorconfig",
            name="enabled",
            field=models.BooleanField(
                help_text="Resource will be offered if connector and resource are enabled."
            ),
        ),
        migrations.AlterField(
            model_name="connectorconfig",
            name="id",
            field=models.AutoField(
                help_text="Primary key of ConnectorConfig.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="connectorconfig",
            name="name",
            field=models.CharField(
                help_text="Human readable name. This must be identificable and unique.",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="connectorconfig",
            name="uri",
            field=models.TextField(
                help_text='This can have and http/s API or database URI. Ex. "https://domain.es/file.ext" '
                'or "oracle://username:password@host".',
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="resourceconfig",
            name="connector_config",
            field=models.ForeignKey(
                help_text="Foreign key of ResourceConfig.",
                on_delete=django.db.models.deletion.CASCADE,
                to="gaodcore_manager.connectorconfig",
            ),
        ),
        migrations.AlterField(
            model_name="resourceconfig",
            name="enabled",
            field=models.BooleanField(
                help_text="Resource will be offered if ConnectorConfig and ResourceConfig are enabled."
            ),
        ),
        migrations.AlterField(
            model_name="resourceconfig",
            name="id",
            field=models.AutoField(
                help_text="Primary key of ResourceConfig.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="resourceconfig",
            name="name",
            field=models.CharField(
                help_text="Human readable name. This must be identificable and unique.",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="resourceconfig",
            name="object_location",
            field=models.CharField(
                help_text="Only used in database resources. it can be a table, view, function, etc. APIs resources"
                " must be null.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="resourceconfig",
            name="object_location_schema",
            field=models.CharField(
                help_text="Only used in database resources. Is not required if are in default schema. APIs resources "
                "must be null.",
                max_length=255,
                null=True,
            ),
        ),
    ]
