# Generated by Django 3.1.14 on 2024-09-12 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaodcore_manager', '0002_auto_20240704_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcesizeconfig',
            name='resource_id',
            field=models.OneToOneField(help_text='Foreign key of ResourceConfig.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gaodcore_manager.resourceconfig'),
        ),
    ]
