# Generated by Django 4.2.16 on 2025-07-18 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaodcore_manager', '0003_auto_20240912_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectorconfig',
            options={'verbose_name': 'Connector Configuration', 'verbose_name_plural': 'Connector Configurations'},
        ),
        migrations.AlterModelOptions(
            name='resourceconfig',
            options={'verbose_name': 'Resource Configuration', 'verbose_name_plural': 'Resource Configurations'},
        ),
        migrations.AlterField(
            model_name='connectorconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='connectorconfig',
            name='enabled',
            field=models.BooleanField(help_text='Resource will be offered if connector and resource are enabled.', verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='connectorconfig',
            name='name',
            field=models.CharField(help_text='Human readable name. This must be identificable and unique.', max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='connectorconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='connectorconfig',
            name='uri',
            field=models.TextField(help_text="This can have and http/s API or database URI. Ex. 'https://domain.es/file.ext' or 'oracle://username:password@host'.", unique=True, verbose_name='URI'),
        ),
        migrations.AlterField(
            model_name='resourceconfig',
            name='connector_config',
            field=models.ForeignKey(help_text='Foreign key of ResourceConfig.', on_delete=django.db.models.deletion.CASCADE, to='gaodcore_manager.connectorconfig', verbose_name='Connector Configuration'),
        ),
        migrations.AlterField(
            model_name='resourceconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='resourceconfig',
            name='enabled',
            field=models.BooleanField(help_text='Resource will be offered if ConnectorConfig and ResourceConfig are enabled.', verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='resourceconfig',
            name='name',
            field=models.CharField(help_text='Human readable name. This must be identificable and unique.', max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='resourceconfig',
            name='object_location',
            field=models.CharField(help_text='Only used in database resources. it can be a table, view, function, etc. APIs resources must be null.', max_length=255, null=True, verbose_name='Object Location'),
        ),
        migrations.AlterField(
            model_name='resourceconfig',
            name='object_location_schema',
            field=models.CharField(help_text='Only used in database resources. Is not required if are in default schema. APIs resources must be null.', max_length=255, null=True, verbose_name='Object Location Schema'),
        ),
        migrations.AlterField(
            model_name='resourceconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
