# Generated by Django 3.1.13 on 2021-07-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Google_Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=250)),
                ('api_version', models.CharField(max_length=250)),
                ('key_file_location', models.CharField(max_length=250)),
                ('service_account_email', models.CharField(max_length=250)),
            ],
        ),
    ]
