# Generated by Django 4.2.16 on 2025-07-18 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gaodcore_manager', '0004_alter_connectorconfig_options_and_more'),
        ('gaodcore_health', '0002_resourcehealthcheckresult_resourcehealthcheckalert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthcheckalert',
            options={'ordering': ['connector__name', 'alert_type'], 'verbose_name': 'Health Check Alert', 'verbose_name_plural': 'Health Check Alerts'},
        ),
        migrations.AlterModelOptions(
            name='healthcheckresult',
            options={'ordering': ['-check_time'], 'verbose_name': 'Health Check Result', 'verbose_name_plural': 'Health Check Results'},
        ),
        migrations.AlterModelOptions(
            name='healthcheckschedule',
            options={'ordering': ['name'], 'verbose_name': 'Health Check Schedule', 'verbose_name_plural': 'Health Check Schedules'},
        ),
        migrations.AlterModelOptions(
            name='resourcehealthcheckalert',
            options={'ordering': ['resource__name', 'alert_type'], 'verbose_name': 'Resource Health Check Alert', 'verbose_name_plural': 'Resource Health Check Alerts'},
        ),
        migrations.AlterModelOptions(
            name='resourcehealthcheckresult',
            options={'ordering': ['-check_time'], 'verbose_name': 'Resource Health Check Result', 'verbose_name_plural': 'Resource Health Check Results'},
        ),
        migrations.AlterField(
            model_name='healthcheckalert',
            name='alert_type',
            field=models.CharField(choices=[('failure', 'Failure'), ('recovery', 'Recovery'), ('timeout', 'Timeout'), ('consecutive_failures', 'Consecutive Failures')], default='failure', help_text='Type of alert (failure, recovery, timeout, consecutive_failures)', max_length=50, verbose_name='Alert Type'),
        ),
        migrations.AlterField(
            model_name='healthcheckalert',
            name='connector',
            field=models.ForeignKey(help_text='The connector to monitor for alerts', on_delete=django.db.models.deletion.CASCADE, to='gaodcore_manager.connectorconfig', verbose_name='Connector'),
        ),
        migrations.AlterField(
            model_name='healthcheckalert',
            name='consecutive_failures_threshold',
            field=models.IntegerField(default=3, help_text='Number of consecutive failures before triggering alert', verbose_name='Consecutive Failures Threshold'),
        ),
        migrations.AlterField(
            model_name='healthcheckalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='healthcheckalert',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this alert is active', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='healthcheckalert',
            name='last_alert_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last alert sent', null=True, verbose_name='Last Alert Time'),
        ),
        migrations.AlterField(
            model_name='healthcheckalert',
            name='threshold_minutes',
            field=models.IntegerField(default=5, help_text='Threshold in minutes before triggering alert', verbose_name='Threshold (minutes)'),
        ),
        migrations.AlterField(
            model_name='healthcheckalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='healthcheckresult',
            name='check_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the health check was performed', verbose_name='Check Time'),
        ),
        migrations.AlterField(
            model_name='healthcheckresult',
            name='connector',
            field=models.ForeignKey(help_text='The connector that was checked', on_delete=django.db.models.deletion.CASCADE, to='gaodcore_manager.connectorconfig', verbose_name='Connector'),
        ),
        migrations.AlterField(
            model_name='healthcheckresult',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if health check failed', null=True, verbose_name='Error Message'),
        ),
        migrations.AlterField(
            model_name='healthcheckresult',
            name='error_type',
            field=models.CharField(blank=True, help_text='Type of error (connection_error, timeout, unknown_error, etc.)', max_length=100, null=True, verbose_name='Error Type'),
        ),
        migrations.AlterField(
            model_name='healthcheckresult',
            name='is_healthy',
            field=models.BooleanField(help_text='Whether the connector is healthy (True) or not (False)', verbose_name='Is Healthy'),
        ),
        migrations.AlterField(
            model_name='healthcheckresult',
            name='response_time_ms',
            field=models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True, verbose_name='Response Time (ms)'),
        ),
        migrations.AlterField(
            model_name='healthcheckschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='healthcheckschedule',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Whether this schedule is enabled', verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='healthcheckschedule',
            name='interval_minutes',
            field=models.IntegerField(default=5, help_text='Interval between health checks in minutes', verbose_name='Interval (minutes)'),
        ),
        migrations.AlterField(
            model_name='healthcheckschedule',
            name='last_run',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last health check run', null=True, verbose_name='Last Run'),
        ),
        migrations.AlterField(
            model_name='healthcheckschedule',
            name='name',
            field=models.CharField(help_text='Name of the health check schedule', max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='healthcheckschedule',
            name='next_run',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the next scheduled health check', null=True, verbose_name='Next Run'),
        ),
        migrations.AlterField(
            model_name='healthcheckschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='resourcehealthcheckalert',
            name='alert_type',
            field=models.CharField(choices=[('failure', 'Failure'), ('recovery', 'Recovery'), ('timeout', 'Timeout'), ('consecutive_failures', 'Consecutive Failures')], default='failure', help_text='Type of alert (failure, recovery, timeout, consecutive_failures)', max_length=50, verbose_name='Alert Type'),
        ),
        migrations.AlterField(
            model_name='resourcehealthcheckalert',
            name='consecutive_failures_threshold',
            field=models.IntegerField(default=3, help_text='Number of consecutive failures before triggering alert', verbose_name='Consecutive Failures Threshold'),
        ),
        migrations.AlterField(
            model_name='resourcehealthcheckalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='resourcehealthcheckalert',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this alert is active', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='resourcehealthcheckalert',
            name='last_alert_time',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last alert sent', null=True, verbose_name='Last Alert Time'),
        ),
        migrations.AlterField(
            model_name='resourcehealthcheckalert',
            name='resource',
            field=models.ForeignKey(help_text='The resource to monitor for alerts', on_delete=django.db.models.deletion.CASCADE, to='gaodcore_manager.resourceconfig', verbose_name='Resource'),
        ),
        migrations.AlterField(
            model_name='resourcehealthcheckalert',
            name='threshold_minutes',
            field=models.IntegerField(default=5, help_text='Threshold in minutes before triggering alert', verbose_name='Threshold (minutes)'),
        ),
        migrations.AlterField(
            model_name='resourcehealthcheckalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='resourcehealthcheckresult',
            name='check_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the health check was performed', verbose_name='Check Time'),
        ),
        migrations.AlterField(
            model_name='resourcehealthcheckresult',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if health check failed', null=True, verbose_name='Error Message'),
        ),
        migrations.AlterField(
            model_name='resourcehealthcheckresult',
            name='error_type',
            field=models.CharField(blank=True, help_text='Type of error (connection_error, timeout, object_error, unknown_error, etc.)', max_length=100, null=True, verbose_name='Error Type'),
        ),
        migrations.AlterField(
            model_name='resourcehealthcheckresult',
            name='is_healthy',
            field=models.BooleanField(help_text='Whether the resource is healthy (True) or not (False)', verbose_name='Is Healthy'),
        ),
        migrations.AlterField(
            model_name='resourcehealthcheckresult',
            name='resource',
            field=models.ForeignKey(help_text='The resource that was checked', on_delete=django.db.models.deletion.CASCADE, to='gaodcore_manager.resourceconfig', verbose_name='Resource'),
        ),
        migrations.AlterField(
            model_name='resourcehealthcheckresult',
            name='response_time_ms',
            field=models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True, verbose_name='Response Time (ms)'),
        ),
    ]
