# Generated by Django 4.2.16 on 2025-09-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaodcore_health', '0003_alter_healthcheckalert_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcheckresult',
            name='error_type',
            field=models.CharField(blank=True, choices=[('connection_error', 'Connection Error'), ('object_error', 'Object Error'), ('timeout', 'Timeout'), ('network_error', 'Network Error'), ('unknown_error', 'Unknown Error')], help_text='Type of error that occurred during health check', max_length=200, null=True, verbose_name='Error Type'),
        ),
        migrations.AlterField(
            model_name='resourcehealthcheckresult',
            name='error_type',
            field=models.CharField(blank=True, choices=[('connection_error', 'Connection Error'), ('object_error', 'Object Error'), ('timeout', 'Timeout'), ('network_error', 'Network Error'), ('connector_failed', 'Connector Failed'), ('unknown_error', 'Unknown Error')], help_text='Type of error that occurred during health check', max_length=200, null=True, verbose_name='Error Type'),
        ),
    ]
